const words = ['Expanded','Ball','set','SAS','Sleek','web','SDD','Rupee','FTP','Bedfordshire','HTTP','reintermediate','azure','of','Directives',
'Missouri','communities','logistical','invoice','Tasty','Pakistan','copy','deliver','database','Chicken','Usability','Taiwan','Small','Togo','feed','back',
'Proactive','override','Account','Shirt','Metrics','Interactions','distributed','Gibraltar','Identity','Kentucky','viral','Manager','scalable','firewall',
'bricks-and-clicks','Rubber','discrete','intangible','Dollar','bluetooth','Customer','Mews','quantify','Practical','violet','high-level','Wooden','lavender',
'Senior','Composite','Dynamic','bypassing','Mouse','withdrawal','Games','Assistant','Direct','Gorgeous','virtual','Optimization','Chair','Soft','Iceland','Colombia',
'Oklahoma','granular','Technician','Montana','payment','Concrete','Executive','Brand','Causeway','Hat','Dinar','e-tailers','International','Internal',
'Re-contextualized','transmit','Central','Forward','Product','XSS','empower','Computer','Philippines','Fantastic','Tonga','Nebraska','calculate','South',
'Ports','Producer','Markets','U.S.','aggregate','Handcrafted','Awesome','Coordinator','transitional','one-to-one','ROI','Uzbekistan','indigo','Shoes',
'Intelligent','Planner','EXE','Health','Metal','Plastic','Money','deposit','Port','Guyana','deploy','online','monitor','Refined','content','cutting-edge',
'sensor','Investment','programming','Sports','copying','mobile','Finland','pixel','Carolina','wireless','Keys','stable','monetize','Regional','customized',
'Synchronised','hack','Yemeni','Group','program','Steel','navigate','collaborative','product','Automotive','maximize','Handmade','Cotton','Wisconsin','hacking',
'Quality-focused','focus','AGP','web-readiness','Avon','Maryland','Berkshire','zero','Guilder','eyeballs','Vision-oriented','markets','Principal','expedite','parse',
'Bosnia','Timor-Leste','Industrial','niches','navigating','magenta','Auto','card','multi-tasking','Ergonomic','Republic','Buckinghamshire','haptic','scale',
'back-end','Division','integrated','backing','Incredible','Investor','New','Home','real-time','cross-platform','e-business','Circle','Licensed','Corporate',
'gold','pricing','and','Palladium','Rwanda','matrix','Persistent','proactive','syndicate','index','Indiana','Multi-tiered','algorithm','compress','harness',
'Bike','boliviano','system','Web','convergence','customer','Algeria','Response','plum','port','orchid','Toys','enterprise','Pound','conglomeration','solutions',
'HDD','overriding','Persevering','Engineer','District','Card','e-commerce','Balanced','Solutions','PNG','Frozen','CFP','firmware','superstructure','schemas',
'explicit','Paradigm','Loan','Towels','Global','red','protocol','transform','Palau','Granite','neural','user-centric','asynchronous','Keyboard','Ngultrum',
'synergy','synthesize','Egypt','Azerbaijanian','Books','Angola','digital','Clothing','enhance','Pants','connect','even-keeled','Djibouti','Rhode','connecting',
'black','optimize','Balboa','Netherlands','purple','Bacon','Director','Universal','Tanzanian','Tuna','Taka','Factors','Texas','Implemented','Reactive','Customizable',
'Stream','alarm','facilitate','States','applications','grid-enabled','Cambridgeshire','tan','transmitting','maroon','Computers','sky','infomediaries','lime'];
export default words;